### ISSUE TITLE
Fantastic job here

### ISSUE THREAD

**Issue by JulesverneOnGitHub** [lipkau/WinSCP.ahk#1]
Regular FTP works great. Your examples are simple to understand and implement.  I was wondering if you have any plans to add Sftp implementation? Is the dll file your creation or from WinSCP site? If you believe Sftp implementation is already available in this build, can you add an example for that?  I have had no luck here.  Thanks! Jules  Again, great job!

**Comment by lipkau** [comment]
I do expect SFTP to be supported, as I use the WinSCP dll, which states that SFTP is supported.
https://winscp.net/eng/docs/library

I would expect it to look something like this:

```
FTPSession.Hostname	:= "myserver.com"
FTPSession.Protocol 	:= WinSCPEnum.FtpProtocol.Sftp
FTPSession.User		:= "MyUserName"
FTPSession.Password	:= "P@ssw0rd"
FTPSession.Fingerprint    := "ssh-rsa 2048 xx:xx:xx:xx:xx:xx:xx:xx:..."
```

but I will not be able to test this within the next days.

**Comment by JulesverneOnGitHub** [comment]
I did try that already looking at the WinSCP docs and just now again and this always the error I get.

>```
> Oops. . . Something went wrong`n0x80070057 - The parameter is incorrect.
> Source:		WinSCPnet
> Description:	SessionOptions.Protocol is Protocol.Sftp or Protocol.Scp, but SessionOptions.SshHostKeyFingerprint is not set.
> HelpFile:		(null)
> HelpContext:	0
>```

Strange. Thanks for looking into it!

**Comment by JulesverneOnGitHub** [comment]
I wonder if it has to do with this section in winscp.ahk (line 223-234) It doesn't mention Sftp
`		if (StrLen(this.Fingerprint) > 1)
			{
				if (this.Protocol==WinSCPEnum.FtpProtocol.Scp)
					this.SessionOptions.SshHostKeyFingerprint := this.Fingerprint
				else
					this.SessionOptions.TlsHostCertificateFingerprint := this.Fingerprint
			} else {
				if (this.Protocol==WinSCPEnum.FtpProtocol.Scp)
					this.SessionOptions.GiveUpSecurityAndAcceptAnySshHostKey := true
				else
					this.SessionOptions.GiveUpSecurityAndAcceptAnyTlsHostCertificate := true
			}`

**Comment by lipkau** [comment]
yes.
I was just looking at that part of the code.
I would test it with this:

```autohotkey
;~ Fingerprint
		IsEncrypted := this.Secure
		Encryptions := WinSCPEnum.FtpSecure.Implicit "," WinSCPEnum.FtpSecure.ExplicitTls "," WinSCPEnum.FtpSecure.ExplicitSsl
		if (StrLen(this.Fingerprint) > 1)
		{
			if IsEncrypted in %Encryptions%
			{
				if (this.Protocol==WinSCPEnum.FtpProtocol.Scp)
					this.SessionOptions.SshHostKeyFingerprint := this.Fingerprint
				else
					this.SessionOptions.TlsHostCertificateFingerprint := this.Fingerprint
			} else {
				if (this.Protocol==WinSCPEnum.FtpProtocol.Scp || this.Protocol==WinSCPEnum.FtpProtocol.Sftp)
					this.SessionOptions.GiveUpSecurityAndAcceptAnySshHostKey := true
				else
					this.SessionOptions.GiveUpSecurityAndAcceptAnyTlsHostCertificate := true
			}
		}
```

but again... I will only be able to test this next week

**Comment by JulesverneOnGitHub** [comment]
I figured out the problem. Since WinSCP.ahk line 172 is
```this.Secure                  := WinSCPEnum.FtpSecure.None```
and Line 221 is this comparison:
```
Encryptions := WinSCPEnum.FtpSecure.Implicit "," WinSCPEnum.FtpSecure.ExplicitTls "," WinSCPEnum.FtpSecure.ExplicitSsl
if IsEncrypted in %Encryptions%
```
it passes over the if comparison. So I added an "else" clause to it like this:
```		Encryptions := WinSCPEnum.FtpSecure.Implicit "," WinSCPEnum.FtpSecure.ExplicitTls "," WinSCPEnum.FtpSecure.ExplicitSsl
if IsEncrypted in %Encryptions%
		{
			if (StrLen(this.Fingerprint) > 1)
			{
				if (this.Protocol==WinSCPEnum.FtpProtocol.Sftp)
					this.SessionOptions.SshHostKeyFingerprint := this.Fingerprint
				else
					this.SessionOptions.TlsHostCertificateFingerprint := this.Fingerprint
			} else {
					if (this.Protocol==WinSCPEnum.FtpProtocol.Scp || this.Protocol==WinSCPEnum.FtpProtocol.Sftp)
						this.SessionOptions.GiveUpSecurityAndAcceptAnySshHostKey := true
					else
						this.SessionOptions.GiveUpSecurityAndAcceptAnyTlsHostCertificate := true
			}
		} else {
			this.SessionOptions.SshHostKeyFingerprint := this.Fingerprint
		}
```

**Comment by lipkau** [comment]
That's why I inverted the if statements in my suggestion.

But I am considering retiring explicitssl for sftp

**Comment by JulesverneOnGitHub** [comment]
Ahh.. well glad I figured out the issue. Thanks again and keep up the good work!

**Comment by JulesverneOnGitHub** [comment]
And for posterity, using your suggestions above, example code should be that but I also added in the port number for SFtp.
```
	FTPSession.Port		:= 22
	FTPSession.Hostname	:= "your.server.com"
	FTPSession.Protocol := WinSCPEnum.FtpProtocol.Sftp
	FTPSession.User		:= "yourusername"
	FTPSession.Password	:= "yourpw"
	FTPSession.Fingerprint    := "ssh-ed25519 256 xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx"
```
